version: '3.9'
services:
  db:
    image: postgres:13
    volumes:
      - db_drive_jan:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drivejan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.py create_super_user &&
            python manage.py runserver 0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=drivejan
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

volumes:
  db_drive_jan:

# docker compose build
# docker compose up

# https://www.youtube.com/watch?v=EY74Gzr66os
