# Generated by Django 4.2.14 on 2024-07-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_alter_attachment_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='box.folder'),
        ),
    ]
